name: bytre
description: Cross-platform ide
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  file_icon: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_tabler_icons: ^1.1.1
  google_fonts: ^2.3.1
  image_crop:
    git:
      url:
        https://github.com/xegrox/image_crop
  image_picker: ^0.8.4+2
  implicitly_animated_list: ^2.1.0
  isar: 2.5.0
  isar_flutter_libs: 2.5.0
  mime: ^1.0.1
  nanoid: ^1.0.0
  ordered_set: ^5.0.0
  path_provider: ^2.0.9
  rive: ^0.8.1
  salomon_bottom_bar: ^3.1.0
  tuple: ^2.0.0
  webview_flutter: ^3.0.2

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  isar_generator: 2.5.0
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/editor/dist/